version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consumer-api
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - consumerapi
  mockpa:
    hostname: mock-pa
    container_name: mock-platformapi
    build: ./testing/mock_services/platformapi/.
    ports:
      - 3000:8001
    restart: on-failure
    networks:
      - consumerapi
  consumer-api:
    hostname: consumer-api
    container_name: consumer-api
    environment:
      CONAPI_PA_URL: http://mock-pa:8001
      CONAPI_POSTGRES_NAME: consumer-api
    build:
      context: .
    ports:
      - 6060:6060
    restart: on-failure
    depends_on:
      - postgres
      - mockpa
    networks:
      - consumerapi
networks:
  consumerapi:
    driver: bridge